import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
 import { ThemeProvider } from "@/components/theme-provider";
import Navbar from "@/components/Navbar";
import { WagmiWrapper } from "@/provider/wagmi-provider";  // Updated import
import ResponsiveNavbar from "@/components/secondNavbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});


const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "g-view Review that matters",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en" className="h-full">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased h-full`}>
        <WagmiWrapper>   
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <Navbar />
            <ResponsiveNavbar/>
{/* 
            <div>
              <SidebarProvider defaultOpen={defaultOpen}>
                <div  className="lg:hidden">
                   <AppSidebar collapsible={'icon'} />
                  
                 </div> 

                 <div className="lg:hidden">
                 <SidebarTrigger /> 
                 </div>
                 */}

                {children}
              {/* </SidebarProvider>
            </div> */}

          </ThemeProvider>
        </WagmiWrapper>
      </body>
    </html>
  );
}
